<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Service::query()->delete();

        $services = [
            [
                'title' => 'Wound Care',
                'slug' => 'wound-care',
                'short_description' => 'Professional in-home wound management, sterile dressing changes, post-operative surgical site care, and infection prevention by certified RNs.',
                'description' => '<p>Managing complex wounds, surgical incisions, or chronic ulcers at home requires expert clinical attention. Our registered nurses perform sterile dressing changes, suture/staple removal, Wound VAC management, and continuous monitoring to accelerate recovery and prevent hospital readmissions.</p><ul><li>Sterile dressing changes & incision monitoring</li><li>Diabetic ulcer care & negative pressure wound therapy</li><li>Physician coordination & infection control</li></ul>',
                'meta_title' => 'Wound Care Services | Angels Home Health of Florida',
                'meta_description' => 'Expert in-home clinical wound care and dressing management in Florida.',
                'meta_keywords' => 'wound care, sterile dressing change, surgical wound healing, RN nursing care',
                'image' => 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Pulmonary Care',
                'slug' => 'pulmonary-care',
                'short_description' => 'Comprehensive respiratory care, oxygen therapy monitoring, tracheostomy care, and pulmonary disease management at home.',
                'description' => '<p>Our specialized pulmonary nursing team assists patients with chronic respiratory conditions like COPD, asthma, and pneumonia. We provide oxygen therapy oversight, chest physiotherapy, nebulizer treatments, and vital sign tracking to support healthy breathing.</p><ul><li>Oxygen therapy & nebulizer management</li><li>Tracheostomy & airway care</li><li>Breathing exercises & pulmonary rehab</li></ul>',
                'meta_title' => 'In-Home Pulmonary & Respiratory Care | Angels Home Health',
                'meta_description' => 'Skilled respiratory care and COPD management delivered at home in Florida.',
                'meta_keywords' => 'pulmonary care, COPD nursing, oxygen therapy, respiratory care',
                'image' => 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Orthopedic Care',
                'slug' => 'orthopedic-care',
                'short_description' => 'Post-joint replacement rehab, fracture recovery support, physical therapy, and home mobility enhancement.',
                'description' => '<p>Recovering from hip, knee, or joint replacement surgery is seamless with our orthopedic home care team. We combine skilled nursing wound care with physical therapy mobility exercises to help patients safely walk and regain full motion at home.</p><ul><li>Post-surgical joint replacement rehab</li><li>Gait training & mobility support</li><li>Pain management & safe transfer techniques</li></ul>',
                'meta_title' => 'Orthopedic Rehabilitation & Home Care | Angels Home Health',
                'meta_description' => 'Post-joint replacement and orthopedic rehabilitation in Lake & Orange County.',
                'meta_keywords' => 'orthopedic care, joint replacement rehab, knee surgery recovery, mobility physical therapy',
                'image' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Nutritional Guidance',
                'slug' => 'nutritional-guidance',
                'short_description' => 'Personalized dietary planning, nutritional assessments, enteral/parenteral feeding support, and hydration tracking.',
                'description' => '<p>Proper nutrition is essential for healing and maintaining energy. Our home care team provides tailored dietary guidance for seniors, managing special diets (low sodium, diabetic, cardiac) and tube feeding (PEG/IV nutrition) under physician guidance.</p><ul><li>Custom meal & dietary plan guidance</li><li>Diabetic & renal diet management</li><li>Enteral (tube) & parenteral feeding support</li></ul>',
                'meta_title' => 'Nutritional Guidance & Dietary Support | Angels Home Health',
                'meta_description' => 'Clinical nutrition guidance and tube feeding management at home in Florida.',
                'meta_keywords' => 'nutritional guidance, senior diet plan, tube feeding home care, clinical diet support',
                'image' => 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Medication Education',
                'slug' => 'medication-education',
                'short_description' => 'In-home medication reconciliation, pill management education, side-effect surveillance, and prescription compliance support.',
                'description' => '<p>Managing multiple daily medications can be confusing. Our registered nurses perform complete medication reconciliation, set up pill organizers, educate patients and caregivers on proper dosages, and monitor for adverse drug interactions.</p><ul><li>Comprehensive medication reconciliation</li><li>Weekly pill organizer setup & reminders</li><li>Patient & family dosage education</li></ul>',
                'meta_title' => 'Medication Education & Management | Angels Home Health',
                'meta_description' => 'RN medication reconciliation and dosage management services in Florida.',
                'meta_keywords' => 'medication education, pill management, drug reconciliation, RN medication administration',
                'image' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Fall Prevention',
                'slug' => 'fall-prevention',
                'short_description' => 'In-home safety assessments, balance and stability training, grab bar recommendations, and fall hazard reduction.',
                'description' => '<p>Falls are the leading cause of senior injuries, but most are preventable. Our physical therapists and nurses conduct thorough home safety audits, identify tripping hazards, and implement targeted balance strengthening programs.</p><ul><li>In-home safety & hazard assessments</li><li>Personalized balance & strength training</li><li>Equipment & assistive device recommendations</li></ul>',
                'meta_title' => 'Senior Fall Prevention & Home Safety | Angels Home Health',
                'meta_description' => 'In-home safety assessments and balance rehabilitation to prevent senior falls.',
                'meta_keywords' => 'fall prevention, senior home safety, balance physical therapy, hazard audit',
                'image' => 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Diabetic Education',
                'slug' => 'diabetic-education',
                'short_description' => 'Blood glucose monitoring instruction, insulin administration guidance, foot care, and lifestyle modification support.',
                'description' => '<p>Living with diabetes requires daily vigilance. Our clinical educators instruct patients on accurate blood glucose testing, proper insulin injection techniques, diabetic foot care, and dietary adjustments to keep blood sugar stable.</p><ul><li>Blood glucose monitoring & log tracking</li><li>Insulin administration & safety education</li><li>Diabetic foot inspection & skin care</li></ul>',
                'meta_title' => 'Diabetic Education & Management | Angels Home Health',
                'meta_description' => 'In-home diabetic education, blood sugar tracking, and insulin management in Florida.',
                'meta_keywords' => 'diabetic education, glucose tracking, insulin instruction, diabetic foot care',
                'image' => 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Chronic Disease Management',
                'slug' => 'chronic-disease-management',
                'short_description' => 'Dedicated clinical management for CHF, COPD, hypertension, diabetes, and kidney disease to prevent readmissions.',
                'description' => '<p>Our chronic disease management program empowers patients to control long-term health conditions at home. With regular nursing visits, vital sign tracking, and prompt physician updates, we significantly lower emergency department visits.</p><ul><li>Vital sign tracking & symptom surveillance</li><li>Physician-directed disease management protocols</li><li>Patient education for self-management</li></ul>',
                'meta_title' => 'Chronic Disease Management | Angels Home Health',
                'meta_description' => 'In-home chronic illness management for CHF, COPD, and diabetes in Central Florida.',
                'meta_keywords' => 'chronic disease management, CHF home care, COPD nursing, hypertension monitoring',
                'image' => 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Medical Social Work',
                'slug' => 'medical-social-work',
                'short_description' => 'Community resource connections, financial planning guidance, Medicare navigation, and emotional counseling for families.',
                'description' => '<p>Licensed Medical Social Workers (LCSWs) support patients and family caregivers through complex healthcare transitions. We assist with community resource applications, long-term care planning, and supportive crisis counseling.</p><ul><li>Community resource & benefit assistance</li><li>Long-term care & financial planning guidance</li><li>Family crisis support & emotional counseling</li></ul>',
                'meta_title' => 'Medical Social Work Services | Angels Home Health',
                'meta_description' => 'Clinical social work support, Medicare navigation, and community resources in Florida.',
                'meta_keywords' => 'medical social work, LCSW home health, eldercare planning, community resource assistance',
                'image' => 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Cardiac Care',
                'slug' => 'cardiac-care',
                'short_description' => 'Heart failure monitoring, blood pressure tracking, cardiac symptom surveillance, and post-cardiac surgery recovery.',
                'description' => '<p>Specialized in-home cardiac nursing focuses on managing Congestive Heart Failure (CHF), hypertension, and post-cardiac procedures. Nurses track daily weights, monitor fluid retention, and coordinate closely with your cardiologist.</p><ul><li>Daily weight & edema monitoring for CHF</li><li>Blood pressure surveillance & telemetry</li><li>Post-cardiac surgery recovery management</li></ul>',
                'meta_title' => 'In-Home Cardiac Nursing Care | Angels Home Health',
                'meta_description' => 'Specialized cardiac care and CHF fluid monitoring delivered at home.',
                'meta_keywords' => 'cardiac care, heart failure home nursing, CHF weight monitoring, blood pressure tracking',
                'image' => 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => "Alzheimer's and Dementia Care",
                'slug' => 'alzheimers-and-dementia-care',
                'short_description' => 'Specialized cognitive routines, memory care support, safe environment structuring, and family respite care.',
                'description' => '<p>Caring for a loved one with Alzheimer\'s disease or dementia requires compassion, patience, and specialized care strategies. Our trained nurses and caregivers create calming routines, implement safety measures, and give family members much-needed respite.</p><ul><li>Tailored cognitive & daily routines</li><li>Wandering prevention & home safety</li><li>Caregiver education & respite support</li></ul>',
                'meta_title' => "Alzheimer's & Dementia Memory Care | Angels Home Health",
                'meta_description' => 'Compassionate in-home dementia care and memory support in Florida.',
                'meta_keywords' => 'alzheimers care, dementia home support, memory care florida, senior cognitive care',
                'image' => 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Comprehensive Health Assessments',
                'slug' => 'comprehensive-health-assessments',
                'short_description' => 'In-depth nursing evaluations, vital sign baselines, home safety audits, and individualized care plan development.',
                'description' => '<p>Our skilled nursing team conducts initial and ongoing full-body health assessments. We evaluate vital signs, skin integrity, medication compliance, physical mobility, and home safety to build a personalized care plan tailored to your needs.</p><ul><li>Full-body physical & vital sign evaluation</li><li>Medication & home environment audit</li><li>Individualized physician-approved care plan</li></ul>',
                'meta_title' => 'Comprehensive Health Assessments | Angels Home Health',
                'meta_description' => 'In-home nursing evaluations and physical health assessments in Florida.',
                'meta_keywords' => 'health assessment, nursing evaluation, vital sign check, home health assessment',
                'image' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Community Resource Assistance',
                'slug' => 'community-resource-assistance',
                'short_description' => 'Navigating community support programs, senior assistance services, transportation options, and financial resources.',
                'description' => '<p>Connecting patients to local support networks improves overall quality of life. We help families access community meal programs, medical equipment assistance, caregiver support groups, and senior healthcare benefits.</p><ul><li>Local senior service referrals</li><li>Medicare/Medicaid benefit guidance</li><li>Assistance program application support</li></ul>',
                'meta_title' => 'Community Resource Assistance | Angels Home Health',
                'meta_description' => 'Navigating local Florida senior assistance, Medicare benefits, and community care.',
                'meta_keywords' => 'community resource assistance, senior assistance florida, medicare guidance, elder resources',
                'image' => 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Speech Therapy',
                'slug' => 'speech-therapy',
                'short_description' => 'Speech restoration, swallowing therapy (dysphagia), cognitive communication rehab, and voice exercises.',
                'description' => '<p>Licensed Speech-Language Pathologists (SLPs) work with patients recovering from stroke, brain injury, or neuromuscular conditions. We focus on improving swallowing safety, verbal communication, memory, and cognitive processing.</p><ul><li>Swallowing evaluation & dysphagia therapy</li><li>Speech & language articulation exercises</li><li>Cognitive rehabilitation & memory training</li></ul>',
                'meta_title' => 'Speech & Language Therapy | Angels Home Health',
                'meta_description' => 'In-home speech therapy and swallowing rehabilitation in Central Florida.',
                'meta_keywords' => 'speech therapy, SLP home care, dysphagia rehab, swallowing therapy',
                'image' => 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Occupational Therapy',
                'slug' => 'occupational-therapy',
                'short_description' => 'Fine motor skill retraining, adaptive equipment guidance, and support for daily self-care independence.',
                'description' => '<p>Occupational therapists help patients regain independence in daily activities such as dressing, eating, bathing, and grooming. We evaluate home environments and recommend adaptive tools to make daily living safer and easier.</p><ul><li>Daily living skill retraining (dressing, bathing)</li><li>Adaptive equipment recommendations</li><li>Fine motor function & hand therapy</li></ul>',
                'meta_title' => 'In-Home Occupational Therapy | Angels Home Health',
                'meta_description' => 'Occupational therapy and daily living self-care retraining in Florida.',
                'meta_keywords' => 'occupational therapy, ADL retraining, adaptive equipment, senior independence',
                'image' => 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Physical Therapy',
                'slug' => 'physical-therapy',
                'short_description' => 'Gait training, range-of-motion restoration, pain management, and physical rehabilitation in the comfort of home.',
                'description' => '<p>In-home physical therapy helps patients rebuild strength, mobility, and confidence following surgery, illness, or injury. Licensed PTs design customized exercise routines to improve walking balance and reduce pain.</p><ul><li>Customized mobility & strength exercises</li><li>Gait training & transfer assistance</li><li>Post-surgical joint & muscle rehabilitation</li></ul>',
                'meta_title' => 'In-Home Physical Therapy Services | Angels Home Health',
                'meta_description' => 'Licensed physical therapy, gait rehabilitation, and mobility training at home.',
                'meta_keywords' => 'physical therapy, PT home health, gait training, mobility rehabilitation',
                'image' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Skilled Nursing',
                'slug' => 'skilled-nursing',
                'short_description' => 'Licensed RN clinical care including wound care, IV therapy, catheter management, and post-hospital recovery.',
                'description' => '<p>Our skilled nursing services deliver hospital-standard clinical expertise in your home. Registered Nurses manage IV antibiotic therapy, complex wound care, catheter/colostomy care, and continuous physician progress reports.</p><ul><li>24/7 RN oversight & complex care</li><li>IV therapy & medication administration</li><li>Catheter, colostomy, & ostomy management</li></ul>',
                'meta_title' => 'Skilled Nursing Services | Angels Home Health',
                'meta_description' => 'Licensed RN home nursing care, IV therapy, and catheter care in Florida.',
                'meta_keywords' => 'skilled nursing, RN home health, IV therapy, clinical nursing care',
                'image' => 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?q=80&w=800&auto=format&fit=crop',
                'is_active' => true,
                'is_featured' => true,
            ],
        ];

        foreach ($services as $service) {
            Service::create($service);
        }
    }
}
